### ISSUE TITLE
Add navbar

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [ShreyaPrasad1209/personal-website#2]

**Comment by Visbhavesh** [comment]
!assign me

**Comment by shahgnp** [comment]
Can you assign me this please.

**Comment by codesmith25103** [comment]
I want to work on this issue. Can you please assign me?

**Comment by singhkaran202** [comment]
Hello @ShreyaPrasad1209 , I'd love to work on this if that's OK.
Could you please assign me this?

**Comment by Hasika-11** [comment]
hey can you assign this to me?
